### ISSUE TITLE
consider using JSON structured data for your grammar source

### ISSUE THREAD

**Issue by dbgarf** [blitzkrigberg/horoscope-generator#3]
/public/grammar/generic_grammar.txt is a plain text file separated by newline chars and with a semantically important structure. however, its not in a format that any other software knows how to deal with. if you ever want to use it for something else you will have to write a new parser function to convert the text data into objects in memory you can work with. 

I would suggest structuring the data as JSON so it can be very simply and easily parsed using the builtin (to every modern browser and JS runtime) global object  `JSON.parse()`

http://devdocs.io/javascript/global_objects/json

and an example of what one of your grammar entries might look like structured as JSON 

```
{
  'weight': 4,
  'phrase`: 'S your mother will ActiveVP`,
  'isTerminal': false
}
```

or alternatively, it could just be an array, which is a somewhat simpler structure and more similar to what you already have

```
var phrases = {
  'sentenceStructures': [
    [4, 'S', 'you', 'will', 'be', 'PassiveVP'],
    [1, 'S', 'you', 'may', 'be', 'PassiveVP'],
    [3, 'S', 'you', 'will', 'ActiveVP'],
    etc.
  ]
}
```

finally, I would suggest using a more easily identifiable placeholder symbol for phrases. S or PassiveVP is similar enough to potential real expressions of English that you might sooner or later find yourself working around the fact that the placeholder symbol looks a lot like something that might not be a placeholder. A very simple approach to that might just be to prefix the symbols with something that never occurs in normal written English, like `@@PassiveVP` or something like that.

**Comment by blitzkrigberg** [comment]
All of this was adopted a few weeks ago! Boom--closed.
